version: "3.8"
services:
  mongodb:

    image: mongo
    container_name: mongodb
    ports:
      - 2717:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usergtap
      - MONGO_INITDB_ROOT_PASSWORD=passgtap
  mongo-express:

    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=usergtap
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passgtap
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network


# Use root/example as user/password credentials
#version: '3.1'
#
#services:
#
#  mongo:
#    image: mongo
#    ports:
#      - 2717:27017
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
